spring.data.mongodb.database=smartmeetdb
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
server.port=8889

# App Properties
bezkoder.app.jwtSecret= ======================BezKoder=Spring===========================
bezkoder.app.jwtExpirationMs= 86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khalilhdd8@gmail.com
spring.mail.password=ufxmnxghkorodpne
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.web=DEBUG
#####
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
######
gemini.api.key=AIzaSyDbUoKYMNChLdK-jmcwF64FSjWOZc-yaec
######
upload.directory=uploads/
###########
#google.client-id=164866495803-ng9o1lvtar39kmvgd1k57l3b4lfltile.apps.googleusercontent.com
#google.client-secret=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
#google.auth-uri=https://accounts.google.com/o/oauth2/auth
#google.token-uri=https://oauth2.googleapis.com/token
#google.redirect-uri=http://localhost:8888/
google.client.id=164866495803-ng9o1lvtar39kmvgd1k57l3b4lfltile.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8888/Callback
##############